-- 코드를 입력하세요
SELECT cr.CAR_ID, cr.CAR_TYPE , FLOOR(cr.DAILY_FEE * (1 - crdp.DISCOUNT_RATE / 100) * 30 ) AS FEE  
FROM CAR_RENTAL_COMPANY_CAR AS cr
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS crdp ON crdp.CAR_TYPE = cr.CAR_TYPE
WHERE cr.CAR_ID NOT IN (SELECT crh.CAR_ID 
                      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS crh
                      WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
AND crdp.DURATION_TYPE = '30일 이상'
AND (cr.DAILY_FEE * (1 - crdp.DISCOUNT_RATE / 100) * 30 ) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC , CAR_TYPE , CAR_ID DESC ;

                        