-- 코드를 입력하세요
SELECT f.PRODUCT_ID , f.PRODUCT_NAME , SUM(f.PRICE * o.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS f
JOIN FOOD_ORDER AS o ON f.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY f.PRODUCT_ID , f.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC , PRODUCT_ID; 