-- 코드를 작성해주세요
SELECT i.ID , n.FISH_NAME AS FISH_NAME , i.LENGTH AS LENGTH 
FROM FISH_INFO AS i
JOIN FISH_NAME_INFO AS n
ON i.FISH_TYPE = n.FISH_TYPE
JOIN
    (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
     FROM FISH_INFO
     GROUP BY FISH_TYPE) AS sub
ON i.FISH_TYPE = sub.FISH_TYPE AND i.LENGTH = sub.MAX_LENGTH
WHERE
    i.LENGTH IS NOT NULL
ORDER BY 1;